### ISSUE TITLE
Black magic tool that can save a few megabytes in your base folder

### ISSUE THREAD

**Issue by adem4ik** [mikejsavage/forksow#19]
- get it here (windows only) https://sourceforge.net/projects/nikkhokkho/files/FileOptimizer/14.50.2586/
- "Options" - "Do not create backups"
- drop "base" folder and start "Optimize"

Result: After 3h 45m "base" folder size decreased from 61.9 MB to 51.4 MB
![image](https://user-images.githubusercontent.com/4707112/103176815-6dd28080-488e-11eb-84e3-c961690b27a5.png)
![image](https://user-images.githubusercontent.com/4707112/103176854-af632b80-488e-11eb-99b2-aff4ab6fae95.png)

If you want to get better optimization you can try "Optimization level - Best" (at the cost of much longer time) & "Allow lossy optimizations" in PNG/JPG tabs (at the cost of visual quality loss). It works nicely with JPG/PNG, and less efficiently with OGG/WAV.

Also it can be a good practice to optimize media files before every realese. Or you can try to make it automatically (example https://github.com/SuperTux/supertux/blob/master/tools/png_recompress.sh ) using different open-source tools widely available on le internet. You can find a list of them here https://nikkhokkho.sourceforge.io/static.php?page=FileOptimizer at Description section.

Cheers.

**Comment by mikejsavage** [comment]
wb adem

so I'm not too bothered by this:

- the game is already tiny by game standards
- lots of assets need replacing
- upcoming changes are going to increase game size substantially (physx, new ui) so cutting 10MB is going to become less of a win

that said I do run optipng from time to time and if there are some free wins we may as well

**Comment by adem4ik** [comment]
Well, I can make a pull request with better optimization level tomorrow, if you don't mind.

**Comment by mikejsavage** [comment]
nah don't worry about it. thanks though
