### ISSUE TITLE
Illegal instruction error when trying to start the game

### ISSUE THREAD

**Issue by ernestpasnik** [mikejsavage/forksow#51]
I'm encountering an Illegal instruction error when trying to start the game on my system.
```
hajt@pc:~/Games/cocainediesel$ ./client
Illegal instruction
```
strace https://privatebin.net/?c6730b49226a246f#CSXNLFW3ENtXm3K7QKqMscCCAnxrhJAL5jqQx8GUih8N
uname -a `Linux pc 6.1.0-26-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.112-1 (2024-09-30) x86_64 GNU/Linux`

Let me know if you need more details or if you'd like me to provide specific commands to run in the terminal.

**Comment by mikejsavage** [comment]
resolved on discord, cpu is too old for sse4.2
